# Primer test de habilidades - WorldPanel

A continuación la resolucion del primer test enviado incialmente como un archivo comprimido.

In [72]:
import pandas as pd

1. Leer el archivo ventas.csv y mostrar los primeros 5 registros.

In [73]:
df_ventas = pd.read_csv("test_ventas.csv")
df_productos = pd.read_csv("test_productos.csv")

In [74]:
df_ventas.head(5)

   id_venta       fecha  id_producto id_cliente  cantidad  precio_unitario
0         1  2024-04-26          102        C10         5              200
1         2  2024-05-27          101        C08         5              100
2         3  2024-02-18          102        C08         4              200
3         4  2024-06-19          101        C03         5              100
4         5  2024-06-01          104        C04         2              800

2. Calcular el monto total de cada venta (cantidad * precio_unitario) y agregarlo como nueva
columna.

In [75]:
df_ventas['monto_total'] = df_ventas.cantidad * df_ventas.precio_unitario

df_ventas.head(5)

,id_venta,fecha,id_producto,id_cliente,cantidad,precio_unitario,monto_total
0,1,2024-04-26,102,C10,5,200,1000
1,2,2024-05-27,101,C08,5,100,500
2,3,2024-02-18,102,C08,4,200,800
3,4,2024-06-19,101,C03,5,100,500
4,5,2024-06-01,104,C04,2,800,1600

3. Obtener la suma total de ventas.

In [76]:
print(df_ventas.monto_total.sum())

301350

4. Calcular el promedio de monto vendido por cliente.

In [77]:
client_grouped = df_ventas.groupby('id_cliente')
result = client_grouped.monto_total.agg('mean')

print(result)

id_cliente
C01    1038.461538
C02     908.620690
C03     879.687500
C04     828.125000
C05    1183.333333
C06    1124.242424
C07     986.538462
C08    1113.636364
C09    1240.322581
C10     756.451613
Name: monto_total, dtype: float64

5. Filtrar las ventas donde el monto total sea mayor a $200.

In [78]:
result = df_ventas[df_ventas['monto_total'] > 200]

print(result)

     id_venta       fecha  id_producto id_cliente  cantidad  precio_unitario  \
0           1  2024-04-26          102        C10         5              200
1           2  2024-05-27          101        C08         5              100
2           3  2024-02-18          102        C08         4              200
3           4  2024-06-19          101        C03         5              100
4           5  2024-06-01          104        C04         2              800
..        ...         ...          ...        ...       ...              ...
294       295  2024-03-01          104        C05         5              800
295       296  2024-03-22          101        C09         3              100
297       298  2024-02-01          104        C08         3              800
298       299  2024-01-03          105        C07         4              150
299       300  2024-02-16          101        C06         4              100

     monto_total
0           1000
1            500
2            800
3            500
4           1600
..           ...
294         4000
295          300
297         2400
298          600
299          400

[246 rows x 7 columns]

6. Agrupar por fecha y obtener el total vendido por día

In [79]:
date_grouped = df_ventas.groupby('fecha')
result = date_grouped.monto_total.agg('sum')

print(result)

fecha
2024-01-01    1000
2024-01-02     400
2024-01-03    4000
2024-01-04     150
2024-01-05    1000
              ...
2024-06-24     800
2024-06-25     150
2024-06-26    2600
2024-06-29     300
2024-06-30     600
Name: monto_total, Length: 153, dtype: int64

7. Unir los archivos ventas.csv y productos.csv por id_producto.

In [80]:
df_merge_vp = pd.merge(df_ventas, df_productos, on='id_producto')

df_merge_vp.head(5)

,id_venta,fecha,id_producto,id_cliente,cantidad,precio_unitario,monto_total,nombre_producto,categoria
0,1,2024-04-26,102,C10,5,200,1000,Cuaderno,Papelería
1,2,2024-05-27,101,C08,5,100,500,Lápiz,Papelería
2,3,2024-02-18,102,C08,4,200,800,Cuaderno,Papelería
3,4,2024-06-19,101,C03,5,100,500,Lápiz,Papelería
4,5,2024-06-01,104,C04,2,800,1600,Mochila,Accesorios

8. Agrupar por producto y obtener cuántas unidades se vendieron de cada uno

In [90]:
product_grouped = df_merge_vp.groupby('id_producto')['cantidad'].sum()

product_grouped.head(5)

id_producto
101    203
102    220
103    132
104    184
105    159
Name: cantidad, dtype: int64

9. Obtener el total de ventas por categoría de producto.

In [97]:
df_merge_vp['monto_total'] = df_merge_vp.cantidad * df_merge_vp.precio_unitario
category_grouped = df_merge_vp.groupby('categoria')['monto_total'].sum()

category_grouped.head(5)

categoria
Accesorios     147200
Electrónica     66000
Papelería       88150
Name: monto_total, dtype: int64

10. Listar los 3 productos más vendidos (por cantidad).

In [121]:
sum_category_grouped = df_merge_vp.groupby('nombre_producto').agg(cantidad_total=('cantidad', 'sum'))
sum_category_grouped['rank'] = sum_category_grouped['cantidad_total'].rank(ascending=False)
sum_category_grouped = sum_category_grouped.sort_values(by='rank', ascending=True)

sum_category_grouped.head(3)

                 cantidad_total  rank
nombre_producto
Cuaderno                    220   1.0
Lápiz                       203   2.0
Mochila                     184   3.0